#GD Orders Settings
#Thu Dec 18 14:17:53 CET 2025
accountsFile=C\:\\Git\\GDOrders\\src\\test\\resources\\InternalAccounts_2.xml
exportDir=C\:\\Git\\GDOrders\\src\\test\\resources
mappingFile=C\:\\Git\\GDOrders\\src\\test\\resources\\order-adres-mapping.json
warehouseCode=2
